const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const messages=$('#messages'),empty=$('#empty'),toast=$('#toast'),dialog=$('#dialog'),dialogBody=$('#dialog-body');
let filter='all',runtimeState={selected:'',relay:'connecting',targets:{},streams:{}};
const roleNames={broadcaster:'B',moderator:'M',partner:'P',vip:'V',og:'O',subscriber:'S',follower:'F'};
function el(n,c,t){const x=document.createElement(n);if(c)x.className=c;if(t!==undefined)x.textContent=t;return x}
function notify(text,error=false){toast.textContent=text||'Done';toast.className=error?'show error':'show';clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.className='',3200)}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function applyFilter(node){node.hidden=filter!=='all'&&node.dataset.platform!==filter}
function withoutRenderedEmotes(m){const text=m.text||'',runes=Array.from(text),hidden=new Set;for(const emote of m.emotes||[]){if(!emote.url)continue;const end=Number(emote.end),start=emote.start===undefined?0:Number(emote.start);if(Number.isInteger(start)&&Number.isInteger(end)&&start>=0&&end>=start&&end<runes.length)for(let i=start;i<=end;i++)hidden.add(i)}return runes.filter((_,i)=>!hidden.has(i)).join('').replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').trim()}
function card(m){const a=el('article','message');a.dataset.platform=m.platform;const meta=el('div','meta');meta.append(el('span',`platform ${m.platform}`,m.platform),el('time','time',new Date(m.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})));a.append(meta);const body=el('div','content');if(m.reply)body.append(el('div','reply',`Reply to ${m.reply.author_display_name||'message'}${m.reply.text?`: ${m.reply.text}`:''}`));const author=el('span','author',m.author_display_name||'Unknown');if(/^#[0-9a-f]{6}$/i.test(m.author_color||''))author.style.color=m.author_color;body.append(author);if(Array.isArray(m.roles)&&m.roles.length){const rs=el('span','roles');for(const r of m.roles)rs.append(el('span','role',roleNames[r]||r));body.append(rs)}const emotes=Array.isArray(m.emotes)?m.emotes.filter(e=>e.url):[],visibleText=withoutRenderedEmotes(m);if(visibleText||!emotes.length)body.append(el('div','text',visibleText||m.event_type||''));if(m.paid?.display)body.append(el('div','paid',m.paid.display));if(emotes.length){const es=el('div','emotes');for(const e of emotes){const image=document.createElement('img');image.src=e.url;image.alt=e.name||'emote';image.loading='lazy';image.referrerPolicy='no-referrer';es.append(image)}body.append(es)}a.append(body);applyFilter(a);return a}
function renderState(s){runtimeState=s||runtimeState;const relay=String(runtimeState.relay||'disconnected'),dot=$('#relay-dot');$('#relay-state').textContent=`Relay: ${relay}`;dot.className=`dot ${relay==='connected'?'online':relay.includes('connect')?'warning':''}`;for(const p of ['kick','twitch']){const node=$(`#${p}-status`),stream=runtimeState.streams?.[p],configured=runtimeState.targets?.[p];node.querySelector('strong').textContent=stream?.title||(!configured?'Setup required':stream?.error||(stream?.available?(stream.live?'Live':'Offline'):'Configured'));node.querySelector('small').textContent=stream?(stream.live?`LIVE · ${stream.viewer_count||0} viewers · ${stream.category||'No category'}`:`OFFLINE · ${stream.category||'No category'}`):(configured?'Status not refreshed':'Not configured')}const youtube=$('#youtube-status'),youtubeConfigured=runtimeState.targets?.youtube;youtube.querySelector('strong').textContent=youtubeConfigured?(relay==='connected'?'Connected through relay':'Configured'):'Setup required';youtube.querySelector('small').textContent=youtubeConfigured?'Incoming YouTube chat is supplied by the server relay.':'YouTube is not configured.';$$('[data-target]').forEach(b=>{const selected=b.dataset.target===runtimeState.selected;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))});const target=runtimeState.selected?runtimeState.selected[0].toUpperCase()+runtimeState.selected.slice(1):'';$('#composer-target').textContent=target||'Choose target';$('#message-input').placeholder=target?`Write a message to ${target}…`:'Choose Kick or Twitch first…';$('.send').disabled=!runtimeState.selected}
async function refreshState(){try{renderState(await api('/api/state'))}catch(e){notify(e.message,true)}}
async function action(payload,success='Done'){try{const result=await api('/api/action',{method:'POST',body:JSON.stringify(payload)});if(result.state)renderState(result.state);notify(result.result||success);return true}catch(e){notify(e.message,true);return false}}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));$$('.message').forEach(applyFilter)}));
$('#clear-local').addEventListener('click',()=>{messages.replaceChildren();empty.hidden=false});
$$('[data-target]').forEach(b=>b.addEventListener('click',async()=>{const platform=b.dataset.target,buttons=$$('[data-target]');buttons.forEach(x=>x.disabled=true);$('.send').disabled=true;$('#composer-target').textContent=`Switching to ${platform[0].toUpperCase()+platform.slice(1)}…`;const ok=await action({Action:'select',Platform:platform},`Outgoing target: ${platform[0].toUpperCase()+platform.slice(1)}`);buttons.forEach(x=>x.disabled=false);if(!ok)renderState(runtimeState)}));
$('#composer').addEventListener('submit',async e=>{e.preventDefault();const input=$('#message-input'),text=input.value.trim(),target=runtimeState.selected;if(!text||!target)return;if(await action({Action:'send',Text:text},`Sent to ${target[0].toUpperCase()+target.slice(1)}`)){input.value='';input.style.height='auto'}});
$('#message-input').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=`${Math.min(e.target.scrollHeight,130)}px`});
$('#message-input').addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey||e.isComposing)return;e.preventDefault();$('#composer').requestSubmit()});
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.action;if(type==='title')action({Action:'title',Title:$('#title-input').value});if(type==='category')action({Action:'category',Category:$('#category-input').value});if(type==='ban')action({Action:'ban',Platform:$('#mod-platform').value,User:$('#mod-user').value});if(type==='timeout')action({Action:'timeout',Platform:$('#mod-platform').value,User:$('#mod-user').value,Duration:$('#timeout-duration').value});if(type==='remote-clear'&&confirm('Clear remote chat? This affects the provider, not just this screen.'))action({Action:'clear',Platform:$('#clear-platform').value,Days:Number($('#clear-days').value)})}));
$$('[data-open]').forEach(b=>b.addEventListener('click',async()=>{try{const result=await api('/api/open',{method:'POST',body:JSON.stringify({platform:b.dataset.open})});window.open(result.url,'_blank','noopener,noreferrer')}catch(e){notify(e.message,true)}}));
async function showDialog(kind){try{let data;if(kind==='config'){data=await api('/api/config');$('#dialog-title').textContent='Configuration & health';dialogBody.replaceChildren();const summary=el('div','card');summary.append(el('h3',data.valid&&data.file_mode_ok?'Configuration healthy':'Attention required'));summary.append(el('p',null,data.valid&&data.file_mode_ok?'The configuration validates and its permissions are private.':(data.problems||[]).join('\n')));summary.querySelector('h3').className=data.valid&&data.file_mode_ok?'health-good':'health-bad';dialogBody.append(summary);const pre=document.createElement('pre');pre.textContent=JSON.stringify(data.config,null,2);dialogBody.append(pre)}if(kind==='setup'){data=await api('/api/setup');$('#dialog-title').textContent='Platform setup & OAuth';dialogBody.replaceChildren();for(const guide of data){const c=el('section','card');c.append(el('h3',null,`${guide.platform} · ${guide.status}`),el('code',null,guide.command));const ol=document.createElement('ol');for(const step of guide.steps)ol.append(el('li',null,step));c.append(ol);dialogBody.append(c)}}if(kind==='archive'){data=await api('/api/archive');$('#dialog-title').textContent='Archive statistics';dialogBody.replaceChildren();const c=el('section','card');c.append(el('h3',null,`${data.Total??data.total??0} archived events`),el('p',null,`Schema ${data.SchemaVersion??data.schema_version??'—'} · First ${data.First??data.first??'—'} · Last ${data.Last??data.last??'—'}`));for(const p of data.Platforms??data.platforms??[])c.append(el('p',null,`${p.Platform??p.platform}: ${p.Count??p.count}`));dialogBody.append(c)}dialog.showModal()}catch(e){notify(e.message,true)}}
$$('[data-dialog]').forEach(b=>b.addEventListener('click',()=>showDialog(b.dataset.dialog)));$('#dialog-close').addEventListener('click',()=>dialog.close());
$('#shutdown').addEventListener('click',async()=>{if(!confirm('Shut down Streamchat GUI gracefully?'))return;try{await api('/api/shutdown',{method:'POST',body:'{}'});document.body.innerHTML='<main class="empty"><strong>Streamchat stopped</strong><span>You may close this tab.</span></main>'}catch(e){notify(e.message,true)}});
$$('[data-panel]').forEach(b=>b.addEventListener('click',()=>$('#tools').classList.add('open')));$$('[data-close-panel]').forEach(b=>b.addEventListener('click',()=>$('#tools').classList.remove('open')));$('#refresh-status').addEventListener('click',refreshState);
const events=new EventSource('/events');events.addEventListener('state',e=>{try{renderState(JSON.parse(e.data))}catch{}});events.addEventListener('message',e=>{try{empty.hidden=true;messages.append(card(JSON.parse(e.data)));while(messages.children.length>500)messages.firstElementChild.remove();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}catch{}});events.onerror=()=>{runtimeState.relay='GUI connection lost';renderState(runtimeState)};
refreshState();setInterval(refreshState,60000);
